// Products
export const START_SEARCH_PRODUCTS = 'START_SEARCH_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_SEARCH_PRODUCTS_CONDITIONS = 'SET_SEARCH_PRODUCTS_CONDITIONS'
export const SET_SEARCH_PRODUCTS_ATTRIBUTE_CONDITIONS = 'SET_SEARCH_PRODUCTS_ATTRIBUTE_CONDITIONS'
export const RESET_SEARCH_PRODUCTS_CONDITIONS = 'RESET_SEARCH_PRODUCTS_CONDITIONS'
// Product detail
export const START_FETCH_PRODUCT = 'START_FETCH_PRODUCT'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const CHOOSE_PRODUCT_ATTRIBUTE = 'CHOOSE_PRODUCT_ATTRIBUTE'
export const UPDATE_PRODUCT_SKU = 'UPDATE_PRODUCT_SKU'
// Departments
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS'
// Attributes
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
// carts
export const INITIALIZE_CART = 'INITIALIZE_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CALCULATE_TOTAL_CART = 'CALCULATE_TOTAL_CART'
// Shipping
export const FETCH_SHIPPING_REGIONS = 'FETCH_SHIPPING_REGIONS'