// Products
export const START_SEARCH_PRODUCTS = 'START_SEARCH_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_SEARCH_PRODUCTS_CONDITIONS = 'SET_SEARCH_PRODUCTS_CONDITIONS'
export const SET_SEARCH_PRODUCTS_ATTRIBUTE_CONDITIONS = 'SET_SEARCH_PRODUCTS_ATTRIBUTE_CONDITIONS'
export const RESET_SEARCH_PRODUCTS_CONDITIONS = 'RESET_SEARCH_PRODUCTS_CONDITIONS'
export const SET_PAGINATION_INDEX = 'SET_PAGINATION_INDEX'
// Product detail
export const START_FETCH_PRODUCT = 'START_FETCH_PRODUCT'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const CHOOSE_PRODUCT_ATTRIBUTE = 'CHOOSE_PRODUCT_ATTRIBUTE'
export const UPDATE_PRODUCT_SKU = 'UPDATE_PRODUCT_SKU'
// Departments
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS'
// Attributes
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
// Carts
export const INITIALIZE_CART = 'INITIALIZE_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CALCULATE_TOTAL_CART = 'CALCULATE_TOTAL_CART'
// Shipping
export const FETCH_SHIPPING_REGIONS = 'FETCH_SHIPPING_REGIONS'
// Stripe
export const CREATE_STRIPE_TOKEN = 'CREATE_STRIPE_TOKEN'
// Customer
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const FETCH_CURRENT = 'FETCH_CURRENT'
export const LOGOUT = 'LOGOUT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// Notification
export const TOGGLE_SHOW_NOTIFICATION_MODAL = 'TOGGLE_SHOW_NOTIFICATION_MODAL'
export const SET_NOTIFICATION_MODAL_CONTENT = 'SET_NOTIFICATION_MODAL_CONTENT'
// Search
export const TOGGLE_SHOW_SEARCH_MODAL = 'TOGGLE_SHOW_SEARCH_MODAL'
export const NEW_SEARCH_TEXT = 'NEW_SEARCH_TEXT'
export const START_TEXT_SEARCH_PRODUCTS = 'START_TEXT_SEARCH_PRODUCTS'
export const STOP_TEXT_SEARCH_PRODUCTS = 'STOP_TEXT_SEARCH_PRODUCTS'
export const FETCH_SEARCH_PRODUCTS = 'FETCH_SEARCH_PRODUCTS'