
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_SEARCH_PRODUCTS_CONDITIONS = 'SET_SEARCH_PRODUCTS_CONDITIONS'
export const RESET_SEARCH_PRODUCTS_CONDITIONS = 'RESET_SEARCH_PRODUCTS_CONDITIONS'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const SET_DEPARTMENTS = 'SET_DEPARTMENTS'

export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'